import { createFileRoute } from "@tanstack/react-router";
import { ContentPage, type ContentBlock } from "@/components/content-page";

const SITE_URL = "https://farixai.com";
const PATH = "/p/privacy-policy";
const TITLE = "Privacy Policy | Farix AI";
const DESCRIPTION =
  "Read the Farix AI privacy policy: what data we collect, how managed AI tool sessions work, how we store account information, and the choices you have over your data.";

const blocks: ContentBlock[] = [
  {
    heading: "1. Introduction",
    paragraphs: [
      "Farix AI (\"Farix\", \"we\", \"us\") provides managed access to third-party AI tools such as Veo 3, Gemini Pro and image generation models through an invite-only platform and a companion Chrome extension. This Privacy Policy explains what information we collect, why we collect it, how it is stored and what control you have over it.",
      "By creating an account through an authorised reseller, signing in to the dashboard or installing the Farix extension, you agree to the practices described on this page. If you do not agree, please stop using the platform and ask your reseller to deactivate your account.",
    ],
  },
  {
    heading: "2. Information we collect",
    paragraphs: [
      "We deliberately keep data collection minimal. Farix AI is not an advertising business and we do not sell personal data to anyone.",
    ],
    bullets: [
      "Account information: full name, email address, hashed password, assigned plan, expiry date and the reseller who activated you.",
      "Access records: sign-in timestamps, active device/session identifiers used to enforce single-device login, and the tools assigned to your account.",
      "Billing status: whether your plan is marked paid or unpaid by your reseller, and the amount recorded by the platform owner. We do not store card numbers.",
      "Technical data: browser type, approximate region, and error logs generated by the dashboard or extension.",
      "Analytics: aggregated, non-identifying usage statistics collected via Google Analytics on the public marketing pages.",
    ],
  },
  {
    heading: "3. Information we do not collect",
    bullets: [
      "We do not read, store or analyse the content of your conversations, prompts or generated media inside the third-party tools.",
      "We do not store payment card details — plan payments are handled offline between you and your reseller.",
      "We do not sell, rent or trade personal information with advertisers or data brokers.",
    ],
  },
  {
    heading: "4. Managed sessions and the Chrome extension",
    paragraphs: [
      "Access to tools is delivered by injecting a managed session into the official website of each provider. The extension needs cookie and host permissions for those specific domains so that the tool opens signed in. Those permissions are limited to the tool domains listed in the extension manifest.",
      "Managed sessions are shared infrastructure. Anything you type inside a managed tool is processed by that tool's provider under their own privacy policy, and history may be visible to platform administrators for abuse-prevention purposes. Never enter passwords, financial details, health information or confidential client data into a managed session.",
    ],
  },
  {
    heading: "5. How we use your information",
    bullets: [
      "To create, activate, renew and deactivate accounts and plans.",
      "To enforce plan-based access rules and single-device login.",
      "To provide support through your reseller and troubleshoot access problems.",
      "To detect abuse, credential sharing and activity that risks the underlying tool accounts.",
      "To improve the reliability and performance of the dashboard and extensions.",
    ],
  },
  {
    heading: "6. Third-party services",
    paragraphs: [
      "Farix AI relies on a small number of service providers: Supabase for authentication, database and file storage; Cloudflare for hosting and delivery; Google Analytics for anonymous marketing-page statistics; and the AI providers themselves (Google and OpenAI) whose interfaces you use through managed sessions. Each provider processes data under its own policy, and we recommend reviewing those policies for the tools you use most.",
    ],
  },
  {
    heading: "7. Data retention",
    paragraphs: [
      "Account records are retained for as long as your account is active and for a limited period afterwards so that renewals and support history remain possible. Session and device records are short-lived and are cleared when you sign out, when the session expires, or when the extension is removed. You can request earlier deletion at any time through your reseller.",
    ],
  },
  {
    heading: "8. Security",
    paragraphs: [
      "Access to platform data is protected by row-level security rules, role-based permissions (King, Reseller, User) and encrypted transport. Administrative actions such as creating users or assigning plans are restricted to authorised roles only. No system is perfectly secure, so we also recommend using a strong, unique password and never sharing your credentials.",
    ],
  },
  {
    heading: "9. Your rights",
    bullets: [
      "Request a copy of the account information we hold about you.",
      "Ask for corrections to inaccurate details such as your name or email.",
      "Request deletion of your account and associated records.",
      "Withdraw consent by stopping use of the platform and uninstalling the extension.",
    ],
  },
  {
    heading: "10. Children",
    paragraphs: [
      "Farix AI is not intended for anyone under 13 years of age, and accounts for minors should only be created and supervised by a parent or guardian in line with the terms of the underlying tool providers.",
    ],
  },
  {
    heading: "11. Changes and contact",
    paragraphs: [
      "We may update this policy as the platform evolves. Material changes will be reflected by a new \"last updated\" date on this page. For any privacy question or request, contact us at support@farixai.com or through the reseller who activated your account.",
    ],
  },
];

export const Route = createFileRoute("/p/privacy-policy")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESCRIPTION },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESCRIPTION },
      { property: "og:type", content: "website" },
      { property: "og:url", content: `${SITE_URL}${PATH}` },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:title", content: TITLE },
      { name: "twitter:description", content: DESCRIPTION },
    ],
    links: [{ rel: "canonical", href: `${SITE_URL}${PATH}` }],
  }),
  component: Page,
});

function Page() {
  return (
    <ContentPage
      eyebrow="Legal · Privacy"
      title="Privacy Policy"
      intro="How Farix AI collects, uses and protects your information across the dashboard, managed sessions and browser extension."
      updated="August 2026"
      blocks={blocks}
    />
  );
}
