/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToolsVeo3VideoGenerationRouteImport } from './routes/tools.veo-3-video-generation'
import { Route as ToolsImagen4ImageGenerationRouteImport } from './routes/tools.imagen-4-image-generation'
import { Route as ToolsChatgptAccessRouteImport } from './routes/tools.chatgpt-access'
import { Route as PTermsAndConditionsRouteImport } from './routes/p/terms-and-conditions'
import { Route as PPrivacyPolicyRouteImport } from './routes/p/privacy-policy'
import { Route as PDisclaimerRouteImport } from './routes/p/disclaimer'
import { Route as PContactUsRouteImport } from './routes/p/contact-us'
import { Route as PAboutUsRouteImport } from './routes/p/about-us'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedResellerRouteRouteImport } from './routes/_authenticated/reseller/route'
import { Route as AuthenticatedKingRouteRouteImport } from './routes/_authenticated/king/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedResellerIndexRouteImport } from './routes/_authenticated/reseller/index'
import { Route as AuthenticatedKingIndexRouteImport } from './routes/_authenticated/king/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedResellerUsersRouteImport } from './routes/_authenticated/reseller/users'
import { Route as AuthenticatedResellerToolsRouteImport } from './routes/_authenticated/reseller/tools'
import { Route as AuthenticatedKingToolsRouteImport } from './routes/_authenticated/king/tools'
import { Route as AuthenticatedKingSuspendedRouteImport } from './routes/_authenticated/king/suspended'
import { Route as AuthenticatedKingSettingsRouteImport } from './routes/_authenticated/king/settings'
import { Route as AuthenticatedKingResellersRouteImport } from './routes/_authenticated/king/resellers'
import { Route as AuthenticatedKingNichesRouteImport } from './routes/_authenticated/king/niches'
import { Route as AuthenticatedKingExtensionLabRouteImport } from './routes/_authenticated/king/extension-lab'
import { Route as AuthenticatedKingBlogRouteImport } from './routes/_authenticated/king/blog'
import { Route as AuthenticatedDashboardWhiskRouteImport } from './routes/_authenticated/dashboard/whisk'
import { Route as AuthenticatedDashboardVeo3RouteImport } from './routes/_authenticated/dashboard/veo-3'
import { Route as AuthenticatedDashboardPromptsRouteImport } from './routes/_authenticated/dashboard/prompts'
import { Route as AuthenticatedDashboardGeminiRouteImport } from './routes/_authenticated/dashboard/gemini'
import { Route as AuthenticatedDashboardExtensionHelpRouteImport } from './routes/_authenticated/dashboard/extension-help'
import { Route as AuthenticatedKingToolsIdRouteImport } from './routes/_authenticated/king/tools_.$id'
import { Route as AuthenticatedKingResellersIdRouteImport } from './routes/_authenticated/king/resellers_.$id'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVeo3VideoGenerationRoute =
  ToolsVeo3VideoGenerationRouteImport.update({
    id: '/tools/veo-3-video-generation',
    path: '/tools/veo-3-video-generation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsImagen4ImageGenerationRoute =
  ToolsImagen4ImageGenerationRouteImport.update({
    id: '/tools/imagen-4-image-generation',
    path: '/tools/imagen-4-image-generation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsChatgptAccessRoute = ToolsChatgptAccessRouteImport.update({
  id: '/tools/chatgpt-access',
  path: '/tools/chatgpt-access',
  getParentRoute: () => rootRouteImport,
} as any)
const PTermsAndConditionsRoute = PTermsAndConditionsRouteImport.update({
  id: '/p/terms-and-conditions',
  path: '/p/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PPrivacyPolicyRoute = PPrivacyPolicyRouteImport.update({
  id: '/p/privacy-policy',
  path: '/p/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PDisclaimerRoute = PDisclaimerRouteImport.update({
  id: '/p/disclaimer',
  path: '/p/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PContactUsRoute = PContactUsRouteImport.update({
  id: '/p/contact-us',
  path: '/p/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PAboutUsRoute = PAboutUsRouteImport.update({
  id: '/p/about-us',
  path: '/p/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResellerRouteRoute =
  AuthenticatedResellerRouteRouteImport.update({
    id: '/reseller',
    path: '/reseller',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKingRouteRoute = AuthenticatedKingRouteRouteImport.update({
  id: '/king',
  path: '/king',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellerIndexRoute =
  AuthenticatedResellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedKingIndexRoute = AuthenticatedKingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedKingRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedResellerUsersRoute =
  AuthenticatedResellerUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedResellerToolsRoute =
  AuthenticatedResellerToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => AuthenticatedResellerRouteRoute,
  } as any)
const AuthenticatedKingToolsRoute = AuthenticatedKingToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedKingRouteRoute,
} as any)
const AuthenticatedKingSuspendedRoute =
  AuthenticatedKingSuspendedRouteImport.update({
    id: '/suspended',
    path: '/suspended',
    getParentRoute: () => AuthenticatedKingRouteRoute,
  } as any)
const AuthenticatedKingSettingsRoute =
  AuthenticatedKingSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedKingRouteRoute,
  } as any)
const AuthenticatedKingResellersRoute =
  AuthenticatedKingResellersRouteImport.update({
    id: '/resellers',
    path: '/resellers',
    getParentRoute: () => AuthenticatedKingRouteRoute,
  } as any)
const AuthenticatedKingNichesRoute = AuthenticatedKingNichesRouteImport.update({
  id: '/niches',
  path: '/niches',
  getParentRoute: () => AuthenticatedKingRouteRoute,
} as any)
const AuthenticatedKingExtensionLabRoute =
  AuthenticatedKingExtensionLabRouteImport.update({
    id: '/extension-lab',
    path: '/extension-lab',
    getParentRoute: () => AuthenticatedKingRouteRoute,
  } as any)
const AuthenticatedKingBlogRoute = AuthenticatedKingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedKingRouteRoute,
} as any)
const AuthenticatedDashboardWhiskRoute =
  AuthenticatedDashboardWhiskRouteImport.update({
    id: '/whisk',
    path: '/whisk',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardVeo3Route =
  AuthenticatedDashboardVeo3RouteImport.update({
    id: '/veo-3',
    path: '/veo-3',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardPromptsRoute =
  AuthenticatedDashboardPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardGeminiRoute =
  AuthenticatedDashboardGeminiRouteImport.update({
    id: '/gemini',
    path: '/gemini',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardExtensionHelpRoute =
  AuthenticatedDashboardExtensionHelpRouteImport.update({
    id: '/extension-help',
    path: '/extension-help',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedKingToolsIdRoute =
  AuthenticatedKingToolsIdRouteImport.update({
    id: '/tools_/$id',
    path: '/tools/$id',
    getParentRoute: () => AuthenticatedKingRouteRoute,
  } as any)
const AuthenticatedKingResellersIdRoute =
  AuthenticatedKingResellersIdRouteImport.update({
    id: '/resellers_/$id',
    path: '/resellers/$id',
    getParentRoute: () => AuthenticatedKingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/contact-us': typeof ContactUsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/king': typeof AuthenticatedKingRouteRouteWithChildren
  '/reseller': typeof AuthenticatedResellerRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/p/about-us': typeof PAboutUsRoute
  '/p/contact-us': typeof PContactUsRoute
  '/p/disclaimer': typeof PDisclaimerRoute
  '/p/privacy-policy': typeof PPrivacyPolicyRoute
  '/p/terms-and-conditions': typeof PTermsAndConditionsRoute
  '/tools/chatgpt-access': typeof ToolsChatgptAccessRoute
  '/tools/imagen-4-image-generation': typeof ToolsImagen4ImageGenerationRoute
  '/tools/veo-3-video-generation': typeof ToolsVeo3VideoGenerationRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/extension-help': typeof AuthenticatedDashboardExtensionHelpRoute
  '/dashboard/gemini': typeof AuthenticatedDashboardGeminiRoute
  '/dashboard/prompts': typeof AuthenticatedDashboardPromptsRoute
  '/dashboard/veo-3': typeof AuthenticatedDashboardVeo3Route
  '/dashboard/whisk': typeof AuthenticatedDashboardWhiskRoute
  '/king/blog': typeof AuthenticatedKingBlogRoute
  '/king/extension-lab': typeof AuthenticatedKingExtensionLabRoute
  '/king/niches': typeof AuthenticatedKingNichesRoute
  '/king/resellers': typeof AuthenticatedKingResellersRoute
  '/king/settings': typeof AuthenticatedKingSettingsRoute
  '/king/suspended': typeof AuthenticatedKingSuspendedRoute
  '/king/tools': typeof AuthenticatedKingToolsRoute
  '/reseller/tools': typeof AuthenticatedResellerToolsRoute
  '/reseller/users': typeof AuthenticatedResellerUsersRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/king/': typeof AuthenticatedKingIndexRoute
  '/reseller/': typeof AuthenticatedResellerIndexRoute
  '/king/resellers/$id': typeof AuthenticatedKingResellersIdRoute
  '/king/tools/$id': typeof AuthenticatedKingToolsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/contact-us': typeof ContactUsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/about-us': typeof PAboutUsRoute
  '/p/contact-us': typeof PContactUsRoute
  '/p/disclaimer': typeof PDisclaimerRoute
  '/p/privacy-policy': typeof PPrivacyPolicyRoute
  '/p/terms-and-conditions': typeof PTermsAndConditionsRoute
  '/tools/chatgpt-access': typeof ToolsChatgptAccessRoute
  '/tools/imagen-4-image-generation': typeof ToolsImagen4ImageGenerationRoute
  '/tools/veo-3-video-generation': typeof ToolsVeo3VideoGenerationRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/extension-help': typeof AuthenticatedDashboardExtensionHelpRoute
  '/dashboard/gemini': typeof AuthenticatedDashboardGeminiRoute
  '/dashboard/prompts': typeof AuthenticatedDashboardPromptsRoute
  '/dashboard/veo-3': typeof AuthenticatedDashboardVeo3Route
  '/dashboard/whisk': typeof AuthenticatedDashboardWhiskRoute
  '/king/blog': typeof AuthenticatedKingBlogRoute
  '/king/extension-lab': typeof AuthenticatedKingExtensionLabRoute
  '/king/niches': typeof AuthenticatedKingNichesRoute
  '/king/resellers': typeof AuthenticatedKingResellersRoute
  '/king/settings': typeof AuthenticatedKingSettingsRoute
  '/king/suspended': typeof AuthenticatedKingSuspendedRoute
  '/king/tools': typeof AuthenticatedKingToolsRoute
  '/reseller/tools': typeof AuthenticatedResellerToolsRoute
  '/reseller/users': typeof AuthenticatedResellerUsersRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/king': typeof AuthenticatedKingIndexRoute
  '/reseller': typeof AuthenticatedResellerIndexRoute
  '/king/resellers/$id': typeof AuthenticatedKingResellersIdRoute
  '/king/tools/$id': typeof AuthenticatedKingToolsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/contact-us': typeof ContactUsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/king': typeof AuthenticatedKingRouteRouteWithChildren
  '/_authenticated/reseller': typeof AuthenticatedResellerRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/p/about-us': typeof PAboutUsRoute
  '/p/contact-us': typeof PContactUsRoute
  '/p/disclaimer': typeof PDisclaimerRoute
  '/p/privacy-policy': typeof PPrivacyPolicyRoute
  '/p/terms-and-conditions': typeof PTermsAndConditionsRoute
  '/tools/chatgpt-access': typeof ToolsChatgptAccessRoute
  '/tools/imagen-4-image-generation': typeof ToolsImagen4ImageGenerationRoute
  '/tools/veo-3-video-generation': typeof ToolsVeo3VideoGenerationRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/dashboard/extension-help': typeof AuthenticatedDashboardExtensionHelpRoute
  '/_authenticated/dashboard/gemini': typeof AuthenticatedDashboardGeminiRoute
  '/_authenticated/dashboard/prompts': typeof AuthenticatedDashboardPromptsRoute
  '/_authenticated/dashboard/veo-3': typeof AuthenticatedDashboardVeo3Route
  '/_authenticated/dashboard/whisk': typeof AuthenticatedDashboardWhiskRoute
  '/_authenticated/king/blog': typeof AuthenticatedKingBlogRoute
  '/_authenticated/king/extension-lab': typeof AuthenticatedKingExtensionLabRoute
  '/_authenticated/king/niches': typeof AuthenticatedKingNichesRoute
  '/_authenticated/king/resellers': typeof AuthenticatedKingResellersRoute
  '/_authenticated/king/settings': typeof AuthenticatedKingSettingsRoute
  '/_authenticated/king/suspended': typeof AuthenticatedKingSuspendedRoute
  '/_authenticated/king/tools': typeof AuthenticatedKingToolsRoute
  '/_authenticated/reseller/tools': typeof AuthenticatedResellerToolsRoute
  '/_authenticated/reseller/users': typeof AuthenticatedResellerUsersRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/king/': typeof AuthenticatedKingIndexRoute
  '/_authenticated/reseller/': typeof AuthenticatedResellerIndexRoute
  '/_authenticated/king/resellers_/$id': typeof AuthenticatedKingResellersIdRoute
  '/_authenticated/king/tools_/$id': typeof AuthenticatedKingToolsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/auth'
    | '/contact-us'
    | '/disclaimer'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/dashboard'
    | '/king'
    | '/reseller'
    | '/blog/$slug'
    | '/p/about-us'
    | '/p/contact-us'
    | '/p/disclaimer'
    | '/p/privacy-policy'
    | '/p/terms-and-conditions'
    | '/tools/chatgpt-access'
    | '/tools/imagen-4-image-generation'
    | '/tools/veo-3-video-generation'
    | '/blog/'
    | '/dashboard/extension-help'
    | '/dashboard/gemini'
    | '/dashboard/prompts'
    | '/dashboard/veo-3'
    | '/dashboard/whisk'
    | '/king/blog'
    | '/king/extension-lab'
    | '/king/niches'
    | '/king/resellers'
    | '/king/settings'
    | '/king/suspended'
    | '/king/tools'
    | '/reseller/tools'
    | '/reseller/users'
    | '/dashboard/'
    | '/king/'
    | '/reseller/'
    | '/king/resellers/$id'
    | '/king/tools/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/auth'
    | '/contact-us'
    | '/disclaimer'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/p/about-us'
    | '/p/contact-us'
    | '/p/disclaimer'
    | '/p/privacy-policy'
    | '/p/terms-and-conditions'
    | '/tools/chatgpt-access'
    | '/tools/imagen-4-image-generation'
    | '/tools/veo-3-video-generation'
    | '/blog'
    | '/dashboard/extension-help'
    | '/dashboard/gemini'
    | '/dashboard/prompts'
    | '/dashboard/veo-3'
    | '/dashboard/whisk'
    | '/king/blog'
    | '/king/extension-lab'
    | '/king/niches'
    | '/king/resellers'
    | '/king/settings'
    | '/king/suspended'
    | '/king/tools'
    | '/reseller/tools'
    | '/reseller/users'
    | '/dashboard'
    | '/king'
    | '/reseller'
    | '/king/resellers/$id'
    | '/king/tools/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-us'
    | '/auth'
    | '/contact-us'
    | '/disclaimer'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/_authenticated/dashboard'
    | '/_authenticated/king'
    | '/_authenticated/reseller'
    | '/blog/$slug'
    | '/p/about-us'
    | '/p/contact-us'
    | '/p/disclaimer'
    | '/p/privacy-policy'
    | '/p/terms-and-conditions'
    | '/tools/chatgpt-access'
    | '/tools/imagen-4-image-generation'
    | '/tools/veo-3-video-generation'
    | '/blog/'
    | '/_authenticated/dashboard/extension-help'
    | '/_authenticated/dashboard/gemini'
    | '/_authenticated/dashboard/prompts'
    | '/_authenticated/dashboard/veo-3'
    | '/_authenticated/dashboard/whisk'
    | '/_authenticated/king/blog'
    | '/_authenticated/king/extension-lab'
    | '/_authenticated/king/niches'
    | '/_authenticated/king/resellers'
    | '/_authenticated/king/settings'
    | '/_authenticated/king/suspended'
    | '/_authenticated/king/tools'
    | '/_authenticated/reseller/tools'
    | '/_authenticated/reseller/users'
    | '/_authenticated/dashboard/'
    | '/_authenticated/king/'
    | '/_authenticated/reseller/'
    | '/_authenticated/king/resellers_/$id'
    | '/_authenticated/king/tools_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  AuthRoute: typeof AuthRoute
  ContactUsRoute: typeof ContactUsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PAboutUsRoute: typeof PAboutUsRoute
  PContactUsRoute: typeof PContactUsRoute
  PDisclaimerRoute: typeof PDisclaimerRoute
  PPrivacyPolicyRoute: typeof PPrivacyPolicyRoute
  PTermsAndConditionsRoute: typeof PTermsAndConditionsRoute
  ToolsChatgptAccessRoute: typeof ToolsChatgptAccessRoute
  ToolsImagen4ImageGenerationRoute: typeof ToolsImagen4ImageGenerationRoute
  ToolsVeo3VideoGenerationRoute: typeof ToolsVeo3VideoGenerationRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/veo-3-video-generation': {
      id: '/tools/veo-3-video-generation'
      path: '/tools/veo-3-video-generation'
      fullPath: '/tools/veo-3-video-generation'
      preLoaderRoute: typeof ToolsVeo3VideoGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/imagen-4-image-generation': {
      id: '/tools/imagen-4-image-generation'
      path: '/tools/imagen-4-image-generation'
      fullPath: '/tools/imagen-4-image-generation'
      preLoaderRoute: typeof ToolsImagen4ImageGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/chatgpt-access': {
      id: '/tools/chatgpt-access'
      path: '/tools/chatgpt-access'
      fullPath: '/tools/chatgpt-access'
      preLoaderRoute: typeof ToolsChatgptAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/terms-and-conditions': {
      id: '/p/terms-and-conditions'
      path: '/p/terms-and-conditions'
      fullPath: '/p/terms-and-conditions'
      preLoaderRoute: typeof PTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/privacy-policy': {
      id: '/p/privacy-policy'
      path: '/p/privacy-policy'
      fullPath: '/p/privacy-policy'
      preLoaderRoute: typeof PPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/disclaimer': {
      id: '/p/disclaimer'
      path: '/p/disclaimer'
      fullPath: '/p/disclaimer'
      preLoaderRoute: typeof PDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/contact-us': {
      id: '/p/contact-us'
      path: '/p/contact-us'
      fullPath: '/p/contact-us'
      preLoaderRoute: typeof PContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/about-us': {
      id: '/p/about-us'
      path: '/p/about-us'
      fullPath: '/p/about-us'
      preLoaderRoute: typeof PAboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reseller': {
      id: '/_authenticated/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof AuthenticatedResellerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/king': {
      id: '/_authenticated/king'
      path: '/king'
      fullPath: '/king'
      preLoaderRoute: typeof AuthenticatedKingRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller/': {
      id: '/_authenticated/reseller/'
      path: '/'
      fullPath: '/reseller/'
      preLoaderRoute: typeof AuthenticatedResellerIndexRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/king/': {
      id: '/_authenticated/king/'
      path: '/'
      fullPath: '/king/'
      preLoaderRoute: typeof AuthenticatedKingIndexRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/reseller/users': {
      id: '/_authenticated/reseller/users'
      path: '/users'
      fullPath: '/reseller/users'
      preLoaderRoute: typeof AuthenticatedResellerUsersRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/reseller/tools': {
      id: '/_authenticated/reseller/tools'
      path: '/tools'
      fullPath: '/reseller/tools'
      preLoaderRoute: typeof AuthenticatedResellerToolsRouteImport
      parentRoute: typeof AuthenticatedResellerRouteRoute
    }
    '/_authenticated/king/tools': {
      id: '/_authenticated/king/tools'
      path: '/tools'
      fullPath: '/king/tools'
      preLoaderRoute: typeof AuthenticatedKingToolsRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
    '/_authenticated/king/suspended': {
      id: '/_authenticated/king/suspended'
      path: '/suspended'
      fullPath: '/king/suspended'
      preLoaderRoute: typeof AuthenticatedKingSuspendedRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
    '/_authenticated/king/settings': {
      id: '/_authenticated/king/settings'
      path: '/settings'
      fullPath: '/king/settings'
      preLoaderRoute: typeof AuthenticatedKingSettingsRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
    '/_authenticated/king/resellers': {
      id: '/_authenticated/king/resellers'
      path: '/resellers'
      fullPath: '/king/resellers'
      preLoaderRoute: typeof AuthenticatedKingResellersRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
    '/_authenticated/king/niches': {
      id: '/_authenticated/king/niches'
      path: '/niches'
      fullPath: '/king/niches'
      preLoaderRoute: typeof AuthenticatedKingNichesRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
    '/_authenticated/king/extension-lab': {
      id: '/_authenticated/king/extension-lab'
      path: '/extension-lab'
      fullPath: '/king/extension-lab'
      preLoaderRoute: typeof AuthenticatedKingExtensionLabRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
    '/_authenticated/king/blog': {
      id: '/_authenticated/king/blog'
      path: '/blog'
      fullPath: '/king/blog'
      preLoaderRoute: typeof AuthenticatedKingBlogRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
    '/_authenticated/dashboard/whisk': {
      id: '/_authenticated/dashboard/whisk'
      path: '/whisk'
      fullPath: '/dashboard/whisk'
      preLoaderRoute: typeof AuthenticatedDashboardWhiskRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/veo-3': {
      id: '/_authenticated/dashboard/veo-3'
      path: '/veo-3'
      fullPath: '/dashboard/veo-3'
      preLoaderRoute: typeof AuthenticatedDashboardVeo3RouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/prompts': {
      id: '/_authenticated/dashboard/prompts'
      path: '/prompts'
      fullPath: '/dashboard/prompts'
      preLoaderRoute: typeof AuthenticatedDashboardPromptsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/gemini': {
      id: '/_authenticated/dashboard/gemini'
      path: '/gemini'
      fullPath: '/dashboard/gemini'
      preLoaderRoute: typeof AuthenticatedDashboardGeminiRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/extension-help': {
      id: '/_authenticated/dashboard/extension-help'
      path: '/extension-help'
      fullPath: '/dashboard/extension-help'
      preLoaderRoute: typeof AuthenticatedDashboardExtensionHelpRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/king/tools_/$id': {
      id: '/_authenticated/king/tools_/$id'
      path: '/tools/$id'
      fullPath: '/king/tools/$id'
      preLoaderRoute: typeof AuthenticatedKingToolsIdRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
    '/_authenticated/king/resellers_/$id': {
      id: '/_authenticated/king/resellers_/$id'
      path: '/resellers/$id'
      fullPath: '/king/resellers/$id'
      preLoaderRoute: typeof AuthenticatedKingResellersIdRouteImport
      parentRoute: typeof AuthenticatedKingRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardExtensionHelpRoute: typeof AuthenticatedDashboardExtensionHelpRoute
  AuthenticatedDashboardGeminiRoute: typeof AuthenticatedDashboardGeminiRoute
  AuthenticatedDashboardPromptsRoute: typeof AuthenticatedDashboardPromptsRoute
  AuthenticatedDashboardVeo3Route: typeof AuthenticatedDashboardVeo3Route
  AuthenticatedDashboardWhiskRoute: typeof AuthenticatedDashboardWhiskRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardExtensionHelpRoute:
      AuthenticatedDashboardExtensionHelpRoute,
    AuthenticatedDashboardGeminiRoute: AuthenticatedDashboardGeminiRoute,
    AuthenticatedDashboardPromptsRoute: AuthenticatedDashboardPromptsRoute,
    AuthenticatedDashboardVeo3Route: AuthenticatedDashboardVeo3Route,
    AuthenticatedDashboardWhiskRoute: AuthenticatedDashboardWhiskRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedKingRouteRouteChildren {
  AuthenticatedKingBlogRoute: typeof AuthenticatedKingBlogRoute
  AuthenticatedKingExtensionLabRoute: typeof AuthenticatedKingExtensionLabRoute
  AuthenticatedKingNichesRoute: typeof AuthenticatedKingNichesRoute
  AuthenticatedKingResellersRoute: typeof AuthenticatedKingResellersRoute
  AuthenticatedKingSettingsRoute: typeof AuthenticatedKingSettingsRoute
  AuthenticatedKingSuspendedRoute: typeof AuthenticatedKingSuspendedRoute
  AuthenticatedKingToolsRoute: typeof AuthenticatedKingToolsRoute
  AuthenticatedKingIndexRoute: typeof AuthenticatedKingIndexRoute
  AuthenticatedKingResellersIdRoute: typeof AuthenticatedKingResellersIdRoute
  AuthenticatedKingToolsIdRoute: typeof AuthenticatedKingToolsIdRoute
}

const AuthenticatedKingRouteRouteChildren: AuthenticatedKingRouteRouteChildren =
  {
    AuthenticatedKingBlogRoute: AuthenticatedKingBlogRoute,
    AuthenticatedKingExtensionLabRoute: AuthenticatedKingExtensionLabRoute,
    AuthenticatedKingNichesRoute: AuthenticatedKingNichesRoute,
    AuthenticatedKingResellersRoute: AuthenticatedKingResellersRoute,
    AuthenticatedKingSettingsRoute: AuthenticatedKingSettingsRoute,
    AuthenticatedKingSuspendedRoute: AuthenticatedKingSuspendedRoute,
    AuthenticatedKingToolsRoute: AuthenticatedKingToolsRoute,
    AuthenticatedKingIndexRoute: AuthenticatedKingIndexRoute,
    AuthenticatedKingResellersIdRoute: AuthenticatedKingResellersIdRoute,
    AuthenticatedKingToolsIdRoute: AuthenticatedKingToolsIdRoute,
  }

const AuthenticatedKingRouteRouteWithChildren =
  AuthenticatedKingRouteRoute._addFileChildren(
    AuthenticatedKingRouteRouteChildren,
  )

interface AuthenticatedResellerRouteRouteChildren {
  AuthenticatedResellerToolsRoute: typeof AuthenticatedResellerToolsRoute
  AuthenticatedResellerUsersRoute: typeof AuthenticatedResellerUsersRoute
  AuthenticatedResellerIndexRoute: typeof AuthenticatedResellerIndexRoute
}

const AuthenticatedResellerRouteRouteChildren: AuthenticatedResellerRouteRouteChildren =
  {
    AuthenticatedResellerToolsRoute: AuthenticatedResellerToolsRoute,
    AuthenticatedResellerUsersRoute: AuthenticatedResellerUsersRoute,
    AuthenticatedResellerIndexRoute: AuthenticatedResellerIndexRoute,
  }

const AuthenticatedResellerRouteRouteWithChildren =
  AuthenticatedResellerRouteRoute._addFileChildren(
    AuthenticatedResellerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedKingRouteRoute: typeof AuthenticatedKingRouteRouteWithChildren
  AuthenticatedResellerRouteRoute: typeof AuthenticatedResellerRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedKingRouteRoute: AuthenticatedKingRouteRouteWithChildren,
  AuthenticatedResellerRouteRoute: AuthenticatedResellerRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  AuthRoute: AuthRoute,
  ContactUsRoute: ContactUsRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  PAboutUsRoute: PAboutUsRoute,
  PContactUsRoute: PContactUsRoute,
  PDisclaimerRoute: PDisclaimerRoute,
  PPrivacyPolicyRoute: PPrivacyPolicyRoute,
  PTermsAndConditionsRoute: PTermsAndConditionsRoute,
  ToolsChatgptAccessRoute: ToolsChatgptAccessRoute,
  ToolsImagen4ImageGenerationRoute: ToolsImagen4ImageGenerationRoute,
  ToolsVeo3VideoGenerationRoute: ToolsVeo3VideoGenerationRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
